name: Publish Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: node-terraform-gitlab-provisioner
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true